---

- hosts: all
  become: true
  tasks: 
    - name: install apache2 package (Fedora/RHEL/CentOS)
      dnf:
        name: 
          - httpd
          - php
        state: latest
        update_cache: yes
      when: ansible_os_family == "RedHat"

    - name: install apache2 package (Debian/Ubuntu)
      apt:
        name: 
          - apache2
          - libapache2-mod-php
        state: latest
        update_cache: yes
      when: ansible_os_family == "Ubuntu"